# Travis configuration file
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# Don't build pyup bot's branches, just the pull requests (hopefully)
branches:
    except:
        - /^pyup-update-.*$/

# Don't build pyup bot's branches, just the pull requests (hopefully)
branches:
    except:
        - /^pyup-update-.*$/

# Don't build pyup bot's branches, just the pull requests (hopefully)
branches:
    except:
        - /^pyup-update-.*$/

install:
  - pip install -r requirements.txt -r dev-requirements.txt
  - pip install -e .

env:
  - TEST_TYPE=pytest
  - TEST_TYPE=pylint

script:
  - |
    if [[ $TEST_TYPE == 'pytest' ]]; then
      pytest --version
      pytest;
    fi
  - |
    if [[ $TEST_TYPE == 'pylint' ]]; then
      pylint --version
      pylint --exit-zero src;
    fi
